//! Private UDisks extensions not yet generated by the `udisks2` crate.

use std::collections::HashMap;

use zbus::{
    proxy,
    zvariant::{ObjectPath, OwnedObjectPath, Value},
};

type Options<'a> = HashMap<&'a str, Value<'a>>;

/// UDisks' `GetSubvolumes` item: subvolume ID, parent ID, and path.
type BtrfsSubvolume = (u64, u64, String);

#[proxy(
    interface = "org.freedesktop.UDisks2.Manager.LVM2",
    default_service = "org.freedesktop.UDisks2",
    default_path = "/org/freedesktop/UDisks2/Manager"
)]
pub trait LvmManager {
    fn volume_group_create(
        &self,
        name: &str,
        blocks: &[ObjectPath<'_>],
        options: Options<'_>,
    ) -> zbus::Result<OwnedObjectPath>;
}

#[proxy(
    interface = "org.freedesktop.UDisks2.VolumeGroup",
    default_service = "org.freedesktop.UDisks2"
)]
pub trait VolumeGroup {
    fn delete(&self, options: Options<'_>) -> zbus::Result<()>;
    fn add_device(&self, device: &ObjectPath<'_>, options: Options<'_>) -> zbus::Result<()>;
    fn remove_device(&self, device: &ObjectPath<'_>, options: Options<'_>) -> zbus::Result<()>;
    fn create_plain_volume(
        &self,
        name: &str,
        size: u64,
        options: Options<'_>,
    ) -> zbus::Result<OwnedObjectPath>;

    #[zbus(property, name = "UUID")]
    fn uuid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn size(&self) -> zbus::Result<u64>;
    #[zbus(property, name = "FreeSize")]
    fn free_size(&self) -> zbus::Result<u64>;
    #[zbus(property, name = "LogicalVolumes")]
    fn logical_volumes(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
    #[zbus(property, name = "PhysicalVolumes")]
    fn physical_volumes(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

#[proxy(
    interface = "org.freedesktop.UDisks2.LogicalVolume",
    default_service = "org.freedesktop.UDisks2"
)]
pub trait LogicalVolume {
    fn delete(&self, options: Options<'_>) -> zbus::Result<()>;
    fn resize(&self, size: u64, options: Options<'_>) -> zbus::Result<()>;
    fn activate(&self, options: Options<'_>) -> zbus::Result<OwnedObjectPath>;
    fn deactivate(&self, options: Options<'_>) -> zbus::Result<()>;

    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn size(&self) -> zbus::Result<u64>;
    #[zbus(property)]
    fn active(&self) -> zbus::Result<bool>;
}

#[proxy(
    interface = "org.freedesktop.UDisks2.Filesystem.BTRFS",
    default_service = "org.freedesktop.UDisks2"
)]
pub trait Btrfs {
    fn add_device(&self, device: &ObjectPath<'_>, options: Options<'_>) -> zbus::Result<()>;
    fn remove_device(&self, device: &ObjectPath<'_>, options: Options<'_>) -> zbus::Result<()>;
    fn create_subvolume(&self, name: &str, options: Options<'_>) -> zbus::Result<()>;
    fn remove_subvolume(&self, name: &str, options: Options<'_>) -> zbus::Result<()>;
    fn create_snapshot(
        &self,
        source: &str,
        destination: &str,
        readonly: bool,
        options: Options<'_>,
    ) -> zbus::Result<()>;
    fn resize(&self, size: u64, options: Options<'_>) -> zbus::Result<()>;
    fn set_label(&self, label: &str, options: Options<'_>) -> zbus::Result<()>;
    #[zbus(name = "SetDefaultSubvolumeID")]
    fn set_default_subvolume_id(&self, id: u32, options: Options<'_>) -> zbus::Result<()>;
    #[zbus(name = "GetSubvolumes")]
    /// UDisks returns `a(tts)i`: subvolume ID, parent ID, path, then count.
    fn get_subvolumes(
        &self,
        snapshots_only: bool,
        options: Options<'_>,
    ) -> zbus::Result<(Vec<BtrfsSubvolume>, i32)>;
    #[zbus(name = "GetDefaultSubvolumeID")]
    fn get_default_subvolume_id(&self, options: Options<'_>) -> zbus::Result<u32>;
}
